baseurl: "/"
languageCode: "en-us"
title: "Pro America"
theme: "xmag"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
hasCJKLanguage: true
paginate: 12

permalinks:
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Live
      url: /
      weight: 1
    - name: Directory
      url: /directory/
      weight: 2
    - name: Feeds
      url: /feeds/
      weight: 3
    - name: Memes
      url: /memes/
      weight: 4
    - name: About
      url: /about/
      weight: 5

params:
  author: "PatriotA"
  description: "PatriotA"
  avatar: "/img/patriotavatar.png"
  headerTitle : "Pro America"
  motto: "The idea of this site is to combine PRO-AMERICA content into one platform that is 100% PRO-AMERICA and nothing else. This is for entertainment purposes. You'll see memes, gifs, and videos all relating to PRO-AMERICA. This website is built on IPFS (InterPlanetary File System), a distributed network that is censorship resistent."
  categoriesLimitInHeader: 6
  favicon: "/img/favicon.ico"
  description: ""
  footer: ""
  github_edit: ""
  summary_length: 300
  text:
    back: "&larr; Back to Home"
    edit: "Edit this page &rarr;"
    truncated: "&hellip;"
  banner:
    src: "/img/cover.png"
    alt: "ProAmerica.Live"
  staticman:
    endpoint: "https://proamerica-staticman-comments.herokuapp.com/v2/entry"
    username: "mrjigglesworth"
    repository: "ProAmerica"
    branch: "main"